In [2]:
# import all packages and set plots to be embedded inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
from pywaffle import Waffle


%matplotlib inline

In [3]:
df = pd.read_csv('/Users/jordanmazza/Desktop/Udacity Files/Project 5/airline_delay_causes.csv')

In [4]:
df.columns = df.columns.str.strip()
df = df.query('year >= 2010').sort_values(['year', 'month'])
df = df.rename(columns={"arr_flights": "flights_total", 
                   "arr_del15": "flights_delayed_total",
                   "arr_cancelled": "flights_cancelled",
                   "arr_diverted": "flights_diverted"})
# df = df.drop(columns = ['carrier', 'airport_name', 'Unnamed: 21'])
df.head()

,year,month,carrier,carrier_name,airport,airport_name,flights_total,flights_delayed_total,carrier_ct,weather_ct,...,late_aircraft_ct,flights_cancelled,flights_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay,Unnamed: 21
28962,2010,1,9E,Pinnacle Airlines Inc.,ABE,"Allentown/Bethlehem/Easton, PA: Lehigh Valley ...",65.0,16.0,5.44,0.00,...,0.00,1.0,0.0,765.0,440.0,0.0,325.0,0.0,0.0,NaN
28963,2010,1,9E,Pinnacle Airlines Inc.,AEX,"Alexandria, LA: Alexandria International",60.0,17.0,4.81,0.49,...,3.81,4.0,0.0,1029.0,297.0,99.0,335.0,0.0,298.0,NaN
28964,2010,1,9E,Pinnacle Airlines Inc.,ALB,"Albany, NY: Albany International",81.0,34.0,9.73,1.42,...,3.28,1.0,1.0,1535.0,533.0,77.0,700.0,0.0,225.0,NaN
28965,2010,1,9E,Pinnacle Airlines Inc.,ALO,"Waterloo, IA: Waterloo Regional",3.0,1.0,0.00,0.00,...,0.00,0.0,0.0,16.0,0.0,0.0,16.0,0.0,0.0,NaN
28966,2010,1,9E,Pinnacle Airlines Inc.,ATL,"Atlanta, GA: Hartsfield-Jackson Atlanta Intern...",1067.0,271.0,42.76,9.40,...,62.78,46.0,4.0,15932.0,4225.0,1098.0,6092.0,0.0,4517.0,NaN